server:
  port: 8081

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6389
      password:
      timeout: 5000

resource:
  counter:
    base-url: http://localhost:8082

springdoc:
  api-docs:
    enabled: true
