server:
  port: 8081



spring:
  application:
    name: dialog
  data:
    redis:
      database: 0
      host: localhost
      port: 6389
      password:
      timeout: 5000

resource:
  counter:
    base-url: http://localhost:8082

springdoc:
  api-docs:
    enabled: true

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram:
    [http.server.requests]: true
  observations:
    key-values:
      application: dialog

