version: '3.3'
services:
  network-backend:
    image: network:0.0.1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - network-db
      - network-cache
      - network-rabbitmq-stomp
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_MASTER_URL=jdbc:postgresql://network-db/network
      - SPRING_DATASOURCE_REPLICA_URL=jdbc:postgresql://network-db/network
      - SPRING_DATA_REDIS_HOST=network-cache
      - SOCKET_RELAY_HOST=network-rabbitmq-stomp

  network-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: network
      POSTGRES_PASSWORD: network
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  network-cache:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  network-rabbitmq-stomp:
    image: network-rabbitmq-stomp:0.0.1
    build:
      context: .
      dockerfile: ./docker/Dockerfile-rabbitmq
    ports:
       - "15672:15672"
       - "61613:61613"
    restart: unless-stopped

volumes:
  db-data: