server:
  port: 8080

spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5500/postgres?useServerPrepStmts=false&rewriteBatchedStatements=true
      username: postgres
      password: network
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
    replica:
      url: jdbc:postgresql://localhost:5500/postgres?useServerPrepStmts=false&rewriteBatchedStatements=true
      username: postgres
      password: network
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yml

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 1000

springdoc:
  api-docs:
    enabled: true

generate-data: false
