server:
  port: 8082

spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5442/network?useServerPrepStmts=false&rewriteBatchedStatements=true
      username: network
      password: network
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
    replica:
      url: jdbc:postgresql://localhost:5442/network?useServerPrepStmts=false&rewriteBatchedStatements=true
      username: network
      password: network
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yml

springdoc:
  api-docs:
    enabled: true
